### ISSUE TITLE
Uncaught TypeError: Failed to construct 'Request': The origin of 'https://t.co/VTFdY6dHFm' should be same as 'https://davidwalsh.name'

### ISSUE THREAD

**Issue by darkwing** [mozilla/wp-offline-shell#81]
When someone clicks a link from Twitter to my blog, which gets masked by their URL shortener (https://t.co/VTFdY6dHFm), the following error is displayed in the console:
<img width="1015" alt="requestcontructerror" src="https://cloud.githubusercontent.com/assets/46655/13683506/a368ae96-e6cc-11e5-9d8b-f8296d2759d0.png">

**Comment by darkwing** [comment]
Adding @delapuente

**Comment by darkwing** [comment]
And this in Firefox where it blocks the page completely:  
<img width="649" alt="corruptedcontent" src="https://cloud.githubusercontent.com/assets/46655/13683774/3b22b370-e6ce-11e5-9fb8-a65b5b4fece3.png">Yikes

**Comment by wanderview** [comment]
I'm interested how chrome did not show an error page as well.  An uncaught exception in the fetch event should force a NetworkError.

**Comment by darkwing** [comment]
(discussion) https://gist.github.com/darkwing/bf42eb527a06f2c259d2

**Comment by delapuente** [comment]
Just for the record. It was 11.00 PM in Madrid when all of this started so I could not join the discussion. We are not crafting a new request for optimization at all. We are doing it to remove the search part (because, as bkelly points, Chrome is not implementing it) and anonymize (in order to allow caching resources outside the site) which is something we've lost with #83. I used this:

```js
return new Request(url, {
  method: request.method,
  headers: request.headers,
  mode: 'no-cors',
  credentials: request.credentials,
  cache: request.cache,
  redirect: request.redirect,
  referrer: request.referrer,
  integrity: request.integrity
});
```

To keep the request as similar as possible to the former request. As eshan says, this error is impossible to catch in normal debugging.

**Comment by darkwing** [comment]
@delapuente Yep, no worries; none of us saw something like this coming as we weren't linking to our local site!  We're all good!
